development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['db_name'] %>
  username: <%= ENV['db_login'] %>
  password: <%= ENV['db_password'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['db_name'] %>
  username: <%= ENV['db_login'] %>
  password: <%= ENV['db_password'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['db_name'] %>
  username: <%= ENV['db_login'] %>
  password: <%= ENV['db_password'] %>
  host: localhost
